import { DataTableUser } from "@/components/data-table";


export const mockUsers: DataTableUser[] = [
  {
    id: "1",
    name: "Maria Silva",
    email: "maria.silva@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    role: "Aluno",
    status: "Ativo",
    createdAt: "12/05/2024",
    lastAccess: "Hoje, 09:15",
  },
  {
    id: "2",
    name: "João Pedro",
    email: "joaopedro@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    role: "Professor",
    status: "Ativo",
    createdAt: "08/04/2024",
    lastAccess: "Hoje, 08:42",
  },
  {
    id: "3",
    name: "Ana Beatriz",
    email: "anabeatriz@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    role: "Aluno",
    status: "Ativo",
    createdAt: "20/06/2024",
    lastAccess: "Ontem, 21:30",
  },
  {
    id: "4",
    name: "Carlos Eduardo",
    email: "carlos.edu@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=51",
    role: "Aluno",
    status: "Inativo",
    createdAt: "15/03/2024",
    lastAccess: "Há 15 dias",
  },
  {
    id: "5",
    name: "Juliana Costa",
    email: "juliana.costa@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
    role: "Professor",
    status: "Ativo",
    createdAt: "11/02/2024",
    lastAccess: "Hoje, 07:50",
  },
  {
    id: "6",
    name: "Rafael Souza",
    email: "rafael.souza@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    role: "Aluno",
    status: "Ativo",
    createdAt: "02/07/2024",
    lastAccess: "Hoje, 10:05",
  },
  {
    id: "7",
    name: "Fernanda Lima",
    email: "fernanda.lima@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
    role: "Professor",
    status: "Inativo",
    createdAt: "28/01/2024",
    lastAccess: "Há 30 dias",
  },
  {
    id: "8",
    name: "Bruno Alves",
    email: "bruno.alves@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=8",
    role: "Aluno",
    status: "Ativo",
    createdAt: "19/05/2024",
    lastAccess: "Há 2 dias",
  },
  {
    id: "9",
    name: "Camila Rocha",
    email: "camila.rocha@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=29",
    role: "Aluno",
    status: "Ativo",
    createdAt: "07/06/2024",
    lastAccess: "Hoje, 11:20",
  },
  {
    id: "10",
    name: "Thiago Martins",
    email: "thiago.martins@email.com",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    role: "Professor",
    status: "Ativo",
    createdAt: "23/03/2024",
    lastAccess: "Ontem, 18:10",
  },
  {
    id: "11",
    name: "Filomeno Segundo",
    email: "filomenoolivetree@gmail.com",
    avatarUrl: "https://github.com/oliveroliveira.png",
    role: "Professor",
    status: "Ativo",
    createdAt: "23/03/2025",
    lastAccess: "Hoje, 11:43"
  }
];